### ISSUE TITLE
non-physical features downwind of fire in qu_wind and wind output variables

### ISSUE THREAD

**Issue by JayCh1** [QF-Error-Tracking/QFVD5#10] opened 2022-12-02 20:48 UTC
**Describe the bug**
Non-physical features appear downwind of the fire in qu_wind and wind output variables. The features appear near the surface and aloft, and are evident in all three wind components. In the windu,v,w variables, diagonally-oriented features that appear to be stronger and more obviously numerical in nature are evident.

**To Reproduce**
netCDF and bin outputs can be found here:

http://35.12.130.8/study/jay/working/qf5/ 

Also included:
QUIC_fire.inp
QU_simparams.inp
sensor1.inp
(all other files are identical to those in the LineFire sample distributed with V5)

**Desktop (please complete the following information):**
 - QF Version 5.1.0
 - OS: Ubuntu

**Screenshots**
The link above includes images from QF 3.1.1, 5.0.2, and 5.1.0 runs with identical inputs. For 5.1.0, here are links to the analyses showing what was discussed during the meeting on Wednesday that David suggested I submit as an issue:

http://35.12.130.8/study/jay/working/qf5/v510_quwindw.png 
http://35.12.130.8/study/jay/working/qf5/v510_windw.png 

(these are both on slices ~35 m above ground level)

**Comment by sbrambilla** [comment] 2022-12-16 22:51
Can you send me the png's in an email? The firewall marks them as unsafe and I cannot access them. 
In QFire_Plume_Advanced_User_Inputs.inp, try setting:
line 14 to 0 
line 15 to 10

**Comment by JayCh1** [comment] 2022-12-19 14:52
Sara,

Here are the images and files from the link above:

![v510_windw](https://user-images.githubusercontent.com/73664588/208452019-ab879531-991f-407e-a694-8cd2a1e69f15.png)
![v510_quwindw](https://user-images.githubusercontent.com/73664588/208452046-591c46d5-8b3b-4337-bfd6-75467f944073.png)

[sensor1.inp.txt](https://github.com/QF-Error-Tracking/QFVD5/files/10260120/sensor1.inp.txt)
[QU_simparams.inp.txt](https://github.com/QF-Error-Tracking/QFVD5/files/10260125/QU_simparams.inp.txt)
[QUIC_fire.inp.txt](https://github.com/QF-Error-Tracking/QFVD5/files/10260131/QUIC_fire.inp.txt)

Also, line 15 is already set to 10 in the QFire_Plume_Advances_User_Inputs.inp I'm using, but Line 14 is set to 1. I will set it to 0 and report any changes I see. 

Thanks,
--Jay

**Comment by sbrambilla** [comment] 2022-12-19 16:19
Jay

I assume those are ground planes? Qu grid and wind grid are the same thing for us, or do you mean fire grid?

Sara


From: JayCh1 ***@***.***>
Reply-To: QF-Error-Tracking/QFVD5 ***@***.***>
Date: Monday, December 19, 2022 at 07:52
To: QF-Error-Tracking/QFVD5 ***@***.***>
Cc: Sara Brambilla ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [QF-Error-Tracking/QFVD5] non-physical features downwind of fire in qu_wind and wind output variables (Issue #10)


Sara,

Here are the images and files from the link above:

[v510_windw]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/73664588/208452019-ab879531-991f-407e-a694-8cd2a1e69f15.png__;!!Bt8fGhp8LhKGRg!B4AXQ2U_8l8yzEaikB_4odzPsF5dzSLRvaSrq4jXiZn8KigYXFcehuhSk3XWWqfHtUg7nyblzMqkuQpCmRY_kiHg3Ys$>
[v510_quwindw]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/73664588/208452046-591c46d5-8b3b-4337-bfd6-75467f944073.png__;!!Bt8fGhp8LhKGRg!B4AXQ2U_8l8yzEaikB_4odzPsF5dzSLRvaSrq4jXiZn8KigYXFcehuhSk3XWWqfHtUg7nyblzMqkuQpCmRY_dUtYu8g$>

sensor1.inp.txt<https://urldefense.com/v3/__https:/github.com/QF-Error-Tracking/QFVD5/files/10260120/sensor1.inp.txt__;!!Bt8fGhp8LhKGRg!B4AXQ2U_8l8yzEaikB_4odzPsF5dzSLRvaSrq4jXiZn8KigYXFcehuhSk3XWWqfHtUg7nyblzMqkuQpCmRY_2x7hGWg$>
QU_simparams.inp.txt<https://urldefense.com/v3/__https:/github.com/QF-Error-Tracking/QFVD5/files/10260125/QU_simparams.inp.txt__;!!Bt8fGhp8LhKGRg!B4AXQ2U_8l8yzEaikB_4odzPsF5dzSLRvaSrq4jXiZn8KigYXFcehuhSk3XWWqfHtUg7nyblzMqkuQpCmRY_jR9fo9Y$>
QUIC_fire.inp.txt<https://urldefense.com/v3/__https:/github.com/QF-Error-Tracking/QFVD5/files/10260131/QUIC_fire.inp.txt__;!!Bt8fGhp8LhKGRg!B4AXQ2U_8l8yzEaikB_4odzPsF5dzSLRvaSrq4jXiZn8KigYXFcehuhSk3XWWqfHtUg7nyblzMqkuQpCmRY_YNCFN8k$>

Also, line 15 is already set to 10 in the QFire_Plume_Advances_User_Inputs.inp I'm using, but Line 14 is set to 1. I will set it to 0 and report any changes I see.

Thanks,
--Jay

**Comment by JayCh1** [comment] 2022-12-19 16:40
Sara,

Those are slices at z=10 (about halfway between the top and bottom of the domain). I set the Number of vertical levels in QUIC_fire.inp to be the same values in QU_simparams.inp (22) so I would have wind values for the entire domain in the qu_windw output variable. Rod indicated that we should be analyzing the qu_windu,v,w output variables preferentially over the windu,v,w output variables for our purposes, so I want the grids to match up as much as possible. 

David indicated during one of our meetings that the qu_wind and wind grids do not necessarily align above the ground because of how grid stretching is applied. The two plots here show the values that appear in the windw and quwindw output variables for level 10. They are clearly not identical, nor can I find any level in the qu_windw outputs that reproduces the features in the windw output at level 10 (there are similarities, but the differences appear too large to my eye to be fully attributable to differences due to stretching).

More shortly when I look at the run it with the new wplume-to-grid scheme. 

--Jay

**Comment by sbrambilla** [comment] 2022-12-19 16:55
Jay,

That’s not how the grids work. Even if they have the same number of levels, the spacing is not the same. I think it’s faster if we talk over the phone about how to set them up. I started adding material in the inputs guide since we keep getting questions about it.

For winds, yes, look at qu_winds*. The others are just interpolated versions of these winds, so no real point in looking at them.

Let me know your availability, I can talk this afternoon until 3:30 Mountain time, or Wed 10-12 and 1-2:30 mountain time. Then I’m leaving for vacation.

Sara

------------------------------------------------------------------------------------------
Sara Brambilla, PhD
Los Alamos National Laboratory
Analytics, Intelligence and Technology Division, Group A-1
+1 505-664-0989
------------------------------------------------------------------------------------------

From: JayCh1 ***@***.***>
Reply-To: QF-Error-Tracking/QFVD5 ***@***.***>
Date: Monday, December 19, 2022 at 09:40
To: QF-Error-Tracking/QFVD5 ***@***.***>
Cc: Sara Brambilla ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [QF-Error-Tracking/QFVD5] non-physical features downwind of fire in qu_wind and wind output variables (Issue #10)


Sara,

Those are slices at z=10 (about halfway between the top and bottom of the domain). I set the Number of vertical levels in QUIC_fire.inp to be the same values in QU_simparams.inp (22) so I would have wind values for the entire domain in the qu_windw output variable. Rod indicated that we should be analyzing the qu_windu,v,w output variables preferentially over the windu,v,w output variables for our purposes, so I want the grids to match up as much as possible.

David indicated during one of our meetings that the qu_wind and wind grids do not necessarily align above the ground because of how grid stretching is applied. The two plots here show the values that appear in the windw and quwindw output variables for level 10. They are clearly not identical, nor can I find any level in the qu_windw outputs that reproduces the features in the windw output at level 10 (there are similarities, but the differences appear too large to my eye to be fully attributable to differences due to stretching).

More shortly when I look at the run it with the new wplume-to-grid scheme.

--Jay

**Comment by JayCh1** [comment] 2022-12-19 17:20
Sara,

I understand how the grids work, and I understand they do not show the same levels. You said above "Qu grid and wind grid are the same thing for us" and I responded by saying the output variables do not show the same values. I'm completely comfortable moving forward using only qu_windu,v,w and ignoring the windu,v,w variables, and I expressed as much to David during the meeting. But he was sufficiently concerned by the differences between the qu_windu,v,w and windu,v,w outputs (differences that appear difficult to explain solely as interpolation issues) that he suggested I report this as an Issue to be sure there is not something else going on here. 

Correct me if I'm wrong @drobinson6045, but I think that was the intent of this exercise.

If you wish to get on the phone to discuss this, please call me at 517-575-0484 at your convenience today (Monday).

--Jay

**Comment by JayCh1** [comment] 2022-12-19 17:29
Update:

I just checked the simulation with the new wplume-to-grid scheme. There are still down-wind perturbations evident in both variables, but now the qu_windw and windw variables are matching up quite well (within what I would expect from interpolating between the two grids).

There are still diagonal features in the winds downwind of the fire in the new simulation that are similar to what appears in the qu_windw figure above. If you would like me to prepare figures from the new run and share them in here, I can do so.

Thanks,
--Jay

**Comment by sbrambilla** [comment] 2022-12-19 17:40
K=10 is not at the same z in the two grids (everything below is in meters). So you won’t see the same picture.
You’ll have to look at k=10 qu_winds* and k=22 in winds* if you want to compare the two.

Num level

DZ QU_simparams

zbottom

zmiddle





DZ QUIC_fire

zbottom

zmiddle

1

1

0

0.5





1

0

0.5

2

1.5

1

1.75





1

1

1.5

3

1.75

2.5

3.375





1

2

2.5

4

2

4.25

5.25





1

3

3.5

5

2.25

6.25

7.375





1

4

4.5

6

2.5

8.5

9.75





1

5

5.5

7

2.75

11

12.375





1

6

6.5

8

3

13.75

15.25





1

7

7.5

9

3.25

16.75

18.375





1

8

8.5

10

3.5

20

21.75





1

9

9.5

11

3.75

23.5

25.375





1

10

10.5

12

4

27.25

29.25





1

11

11.5

13

4.5

31.25

33.5





1

12

12.5

14

5.5

35.75

38.5





1

13

13.5

15

7

41.25

44.75





1

14

14.5

16

8.5

48.25

52.5





1

15

15.5

17

10

56.75

61.75





1

16

16.5

18

11.5

66.75

72.5





1

17

17.5

19

13

78.25

84.75





1

18

18.5

20

26

91.25

104.25





1

19

19.5

21

70

117.25

152.25





1

20

20.5

22

140

187.25

257.25





1

21

21.5



------------------------------------------------------------------------------------------
Sara Brambilla, PhD
Los Alamos National Laboratory
Analytics, Intelligence and Technology Division, Group A-1
+1 505-664-0989
------------------------------------------------------------------------------------------

From: JayCh1 ***@***.***>
Reply-To: QF-Error-Tracking/QFVD5 ***@***.***>
Date: Monday, December 19, 2022 at 10:20
To: QF-Error-Tracking/QFVD5 ***@***.***>
Cc: Sara Brambilla ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [QF-Error-Tracking/QFVD5] non-physical features downwind of fire in qu_wind and wind output variables (Issue #10)


Sara,

I understand how the grids work, and I understand they do not show the same levels. You said above "Qu grid and wind grid are the same thing for us" and I responded by saying the output variables do not show the same values. I'm completely comfortable moving forward using only qu_windu,v,w and ignoring the windu,v,w variables, and I expressed as much to David during the meeting. But he was sufficiently concerned by the differences between the qu_windu,v,w and windu,v,w outputs (differences that appear difficult to explain solely as interpolation issues) that he suggested I report this as an Issue to be sure there is not something else going on here.

Correct me if I'm wrong @drobinson6045<https://urldefense.com/v3/__https:/github.com/drobinson6045__;!!Bt8fGhp8LhKGRg!B14E1qb6MZFLKrRrb2JTx497GB1SqYVyb1W-1bKjo5vwq-vPWYFaC80AHqm0eDM-ikjUq4YElQ88avn_sdb5s8enGGM$>, but I think that was the intent of this exercise.

If you wish to get on the phone to discuss this, please call me at 517-575-0484 at your convenience today (Monday).

--Jay

**Comment by JayCh1** [comment] 2022-12-19 18:31
Sara,

Yes, I see that. Taking a vertical cross section through the two variables makes it clear that with the old wplume-to-grid scheme, there are features in the windw output variable that do not appear in the qu_windw output variable. With the new scheme, the features are identical (but interpolated to different k indices in the variables).

That being the case, I am happy to move forward with using only the qu_wind variables and the new wplume-to-grid scheme. 

If you wish me to do any additional testing to determine why the windu,v,w and qu_windu,v,w differ for the old scheme, please let me know. 

And if/when we are ready to talk about what, if anything, needs to be done to address the downwind perturbations in the qu_windu,v,w variables (because I think these could be important for smoke dispersion simulations?), please let me know as well.

Thanks,
--Jay

**Comment by sbrambilla** [comment] 2022-12-19 18:40
﻿I’m still surprised that the winds are not similar with the old scheme. The interpolator is the same independently of the wplume-to-grid. I’d like to look more into it to see if there’s an issues.

Going forward, we’d like to move to the new wplume-to-grid scheme, but that is much slower than the old one.

For the ground features, I’ll have to check them out again. It may be excessive diffusion from the SOR.


From: JayCh1 ***@***.***>
Reply-To: QF-Error-Tracking/QFVD5 ***@***.***>
Date: Monday, December 19, 2022 at 11:31
To: QF-Error-Tracking/QFVD5 ***@***.***>
Cc: Sara Brambilla ***@***.***>, Comment ***@***.***>
Subject: [EXTERNAL] Re: [QF-Error-Tracking/QFVD5] non-physical features downwind of fire in qu_wind and wind output variables (Issue #10)


Sara,

Yes, I see that. Taking a vertical cross section through the two variables makes it clear that with the old wplume-to-grid scheme, there are features in the windw output variable that do not appear in the qu_windw output variable. With the new scheme, the features are identical (but interpolated to different k indices in the variables).

That being the case, I am happy to move forward with using only the qu_wind variables and the new wplume-to-grid scheme.

If you wish me to do any additional testing to determine why the windu,v,w and qu_windu,v,w differ for the old scheme, please let me know.

And if/when we are ready to talk about what, if anything, needs to be done to address the downwind perturbations in the qu_windu,v,w variables (because I think these could be important for smoke dispersion simulations?), please let me know as well.

Thanks,
--Jay

**Comment by JayCh1** [comment] 2022-12-19 19:51
Here are vertical cross sections of vertical wind speeds (w) for the two runs. Apologies for the rainbow, these are kind of quick and dirty. The only difference between the runs is the change from the old to the new wplume-to-grid scheme. Everything else is identical. 

[aside, in case this is of interest: this run took 15 minutes with the old scheme and 25 minutes with the new scheme on my server. So yes, it is quite a bit slower.]

Looking a these plots more carefully, here are my observations:

1) The top of the wind grid is ~ level 10 in the qu_grid, as indicated by Sara above
2) There is a lot of eye-straining vertical stretching going on here, but some of the higher wind speeds (oranges and reds) near the top of the wind plots (e.g. between grid points 100 and 150) are not evident in the qu_wind plots for either simulation, although the differences look more pronounced to me for the run using the old scheme. 
3) Some of the features in the qu_wind plots appear to be shifted to the left in the wind plots (again, this is most evident to me between grid points 100 and 150 above the main fire perturbations).

There is probably a bit too much to unpack here in an Issues thread, so it might be best to revisit this after the New Year (during a meeting) when we all have a bit more time to dig in on this?

Thanks for all the comments/attention to this issue!
--Jay

new simulation:
![v510_quwindw_vcs_new](https://user-images.githubusercontent.com/73664588/208503828-563951b2-8077-402a-89d5-0125fc1dd547.png)
![v510_windw_vcs_new](https://user-images.githubusercontent.com/73664588/208503849-661d7d44-de1e-48c9-80c6-408d05c7d77f.png)

old simulation:
![v510_quwindw_vcs_old](https://user-images.githubusercontent.com/73664588/208503879-4bac1d8e-d349-4eb7-a6ac-b93ad57e174c.png)
![v510_windw_vcs_old](https://user-images.githubusercontent.com/73664588/208503893-e3a21f58-46b5-46ae-953b-db44c8895944.png)

**Comment by zacharycope0** [comment] 2023-04-19 19:54
It seems that this issue has been resolved in 5.2.2

**Closed as completed by zacharycope0** 2023-04-19 19:54 UTC
