### ISSUE TITLE
v5.1.0 is significantly slower than v4.0.1

### ISSUE THREAD

**Issue by iperezx** [QF-Error-Tracking/QFVD5#9] opened 2022-12-01 16:56 UTC
David is aware of this but wanted to make the issue to keep track of the progress.

**Describe the bug**
QF Runtime for FastFuels

v4.0.1: 255 secs
v5.0.0: 461 secs
v5.1.0: 1712 secs

From the version we have ran before (v4.0.1) we are doing down to almost a 7x slowdown.
All these runtimes are taken directly from timelog.log written by QF using make test

**To Reproduce**
https://swat.sdsc.edu/nc/s/NT6RRbmZi9PPSXd -> outputs.zip

**Desktop (please complete the following information):**
 - QF Version v4.0.1, v5.0.0, and v5.1.0
 - OS: ubuntu

**Screenshots**

**Comment by crawld** [comment] 2022-12-01 17:55
contact me for nextcloud password

**Comment by drosales95** [comment] 2022-12-01 19:35
Hey Ismael! 

I checked in on the runs you sent and I believe the issue is coming mostly from the values you are using in the QU_TopoInputs.inp.

Here are the values you are using right now:
!Specify file name for custom topo (full path)
ftelevation.dat
5              !N/A,Topo flag 0:Flat 1:Gaussian Hill 3:Constant slope with flat section 5:Custom .dat
0              !N/A, smoothing method (0 = none (default for idealized terrain), 1 = blur, 2 = David's)
0     ! N/A, number of smoothing passes
2000   ! N/A, number of initial SOR iterations (only if fire is run)
4     ! N/A, sor cycles
1.3   ! N/A, sor relaxation parameter (default for flat is 1.78, ignored if there is no terrain)
0     ! N/A, add slope flow correction (0 = no, 1 = yes)
!Command to run slope flow code (system specific)
""
**Runtime = 532 s**

Here are the default values:
!Specify file name for custom topo (full path)
ftelevation.dat
5              !N/A,Topo flag 0:Flat 1:Gaussian Hill 3:Constant slope with flat section 5:Custom .dat
2              !N/A, smoothing method (0 = none (default for idealized terrain), 1 = blur, 2 = David's)
200     ! N/A, number of smoothing passes
500   ! N/A, number of initial SOR iterations (only if fire is run)
4     ! N/A, sor cycles
1.3   ! N/A, sor relaxation parameter (default for flat is 1.78, ignored if there is no terrain)
0     ! N/A, add slope flow correction (0 = no, 1 = yes)
!Command to run slope flow code (system specific)
""
**Runtime = 148s**

You can check the default values in the QUIC-Fire_Inputs.pdf in the doc directory.

Could you rerun this with the default values and let me know if you're still seeing large issues with the runtime?

**Comment by iperezx** [comment] 2022-12-01 19:50
Would these default values hold up for most FastFuel cases? How were they determined?

**Comment by iperezx** [comment] 2022-12-02 00:43
@drosales95 

Thanks it got down to 303 so closer to v4.0.1. 

I will make sure to reference the default values in the pdfs.

Do you think this will hold up for any FastFuel cases?

What if we set the smoothing flag to 0? I got 268 secs if I set it to 0.

**Comment by iperezx** [comment] 2022-12-02 18:04
I just realized that I missed this one:
```
2 !N/A, smoothing method (0 = none (default for idealized terrain), 1 = blur, 2 = David's)
```

I am clocked at 247 secs for FF. 

Thanks!

Still curious to know how the SOR and smoothing params are determined.

**Comment by zacharycope0** [comment] 2023-01-04 20:01
I'm closing issues that I believe to be resolved. Please reopen if you still need something addressed.

**Closed as completed by zacharycope0** 2023-01-04 20:01 UTC
